### PR TITLE
wip: minimal working code to filter on index quality in addition to match

### PR DESCRIPTION
**Pull request by dhoogest**
this needs some cleanup, but here's my rough version of the qual filter

### CODE REVIEW

**Comment by dhoogest** [comment]
Note needs more work to handle second index file - I'd worked this up with data that only had single index.

**Comment by tholland** [comment]
I'm not sure how to add an additional file that's been changed to a pull request that isn't already from an existing branch.  I can make a new pull request or you can add the following change to barcodecop/__init__.py:

from os import path

# default values
MIN_QUAL = 26
QUAL_OFFSET = 33  # default is set for Illumina reads

try:
    with open(path.join(path.dirname(__file__), 'data', 'ver')) as f:
        __version__ = f.read().strip().replace('-', '+', 1).replace('-', '.')
except Exception, e:
    __version__ = ''

**Comment by tholland** [comment]
@dhoogest I can't add additional files to your forked repo.  Can you add the following change to `barcodecop/__init__.py`:

```python
from os import path

# default values
MIN_QUAL = 26
QUAL_OFFSET = 33  # default is set for Illumina reads

try:
    with open(path.join(path.dirname(__file__), 'data', 'ver')) as f:
        __version__ = f.read().strip().replace('-', '+', 1).replace('-', '.')
except Exception, e:
    __version__ = ''

**Comment by tholland** [comment]
Using #3 instead of #2 to make collaboration easier.

**Pull request closed without merging**
